import{A as c,S as a,a as l,N as d,P as u,K as f,E as p,C as w,i as m}from"./assets/vendor-B7RKDMKO.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",function(){new c(".accordion-container",{showMultiple:!0,duration:300})});const v=async()=>{const r=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!r.ok)throw new Error(r.status);return await r.json()};function g({author:r,avatar_url:s,review:o}){return`<li class="swiper-slide">
    <div class="reviews-item">
    <div class="element">
        <img class="review-section-img" src="${s}" alt="${r}"  />
        <h3 class="reviews-title">${r}</h3>
        <p class="reviews-text">${o}</p>
        </div>
    </div>
  </li>`}function y(r){return r.map(g).join("")}const h=r=>{const s=document.querySelector(".reviews-section"),o=s.querySelector(".swiper-wrapper"),i=s.querySelector(".swiper-reviews");v().then(e=>{const t=y(e);o.insertAdjacentHTML("beforeend",t),new r(i,{slidesPerView:1,autoHeight:!0,speed:600,spaceBetween:16,keyboard:{enabled:!0,onlyInViewport:!1},breakpoints:{768:{speed:600,autoHeight:!1,slidesPerView:2,spaceBetween:16},1440:{speed:600,autoHeight:!1,slidesPerView:4,spaceBetween:16}},navigation:{nextEl:s.querySelector(".swiper-button-next"),prevEl:s.querySelector(".swiper-button-prev")}})}).catch(e=>{m.error({title:"Error!",titleSize:"16",titleColor:"#fafafa",message:"Reviews not found",messageSize:"16",messageColor:"#fafafa",backgroundColor:"#1C1D20",theme:"dark",position:"bottomCenter",closeOnEscape:!0,closeOnClick:!0}),i.innerHTML='<p class="reviews-notfound">Not found</p>'})};document.addEventListener("DOMContentLoaded",r=>{a.use([l,d,u,f,p,w]),h(a)});
//# sourceMappingURL=commonHelpers.js.map
